### ISSUE TITLE
Segfault when using v0.1.3

### ISSUE THREAD

**Issue by jakebolewski** [JuliaSIMD/TriangularSolve.jl#13]
Here is a representative stack trace:
https://buildkite.com/clima/climacore-ci/builds/183#73896f51-3ec9-4099-a226-3217264ed813/96-100

Culprit looks to be a mis-sized buffer? 
https://github.com/JuliaSIMD/TriangularSolve.jl/blob/08ca19bb924b8856b7fa3be4af4bf53e6a0c2c9a/src/TriangularSolve.jl#L288-L290

This also might be resolved with the latest release that adjusted the compat bounds with `VectorizationBase`

**Comment by chriselrod** [comment]
The buffer looks like it is sized correctly (`N * register_size() * UF`).

**Comment by jakebolewski** [comment]
Looks like updating / pinning to v1.5 fixed the issue, (which also had impacts with dependee  package versions so it's difficult to pin down).

**Comment by chriselrod** [comment]
Hmm. Okay. Let me know if this comes up again on the latest version.

There were recent segfault issues with StrideArraysCore 0.2.0 that have since been fixed in 0.2.1, which the latest Polyester requires. However, TriangularSolve 0.1.3 requires Polyester 0.3, which is limited to StrideArraysCore 0.1.
There're have been other Polyester segfault issues, but all the known ones have been fixed in the latest from the 0.3 and 0.4 series.

**Comment by jakebolewski** [comment]
Thanks @chriselrod, I'll keep this in mind going forward if we see this coming up again.
